### ISSUE TITLE
Running a Node app with Cordova

### ISSUE THREAD

**Issue by harrygfox** [Amigoat/Alpha#2]
@ldarby91 I just found [this article](http://www.sitepoint.com/how-to-run-node-js-with-express-on-mobile-devices/) that I think might be of some use. Let's use this space to talk about it.

**Comment by ldarby91** [comment]
Thanks man, just got home from work so will read this first thing in the morning. I posted some questions in the phonegap forum about a similar thing that people have responded to so I'll get clued up tomorrow. Thanks man.

**Comment by harrygfox** [comment]
> ## Awesome!

**Comment by ldarby91** [comment]
# OMG LOLZ CODE HAHAHAHAHAHAHAHAHA
